### ISSUE TITLE
@bliunlpr 非常感谢，内存不足的问题解决了，再打扰下，训练的时候损失无穷大，不知道为何

### ISSUE THREAD

**Issue by tanglinjie0815** [libai3/masr#134]
@bliunlpr 非常感谢，内存不足的问题解决了，再打扰下，训练的时候损失无穷大，不知道为何
```
[1/1000][1065/32813]    Loss = inf
Warning: NaN or Inf found in input tensor.
[1/1000][1066/32813]    Loss = inf
Warning: NaN or Inf found in input tensor.
[1/1000][1067/32813]    Loss = inf
Warning: NaN or Inf found in input tensor.
[1/1000][1068/32813]    Loss = inf
Warning: NaN or Inf found in input tensor.
```
标记里有英文字符，是这个问题导致？

_Originally posted by @v-yunbin in https://github.com/libai3/masr/issues/51#issuecomment-507514335_

**Comment by wangjianhua1** [comment]
> @bliunlpr 非常感谢，内存不足的问题解决了，再打扰下，训练的时候损失无穷大，不知道为何
> 
> ```
> [1/1000][1065/32813]    Loss = inf
> Warning: NaN or Inf found in input tensor.
> [1/1000][1066/32813]    Loss = inf
> Warning: NaN or Inf found in input tensor.
> [1/1000][1067/32813]    Loss = inf
> Warning: NaN or Inf found in input tensor.
> [1/1000][1068/32813]    Loss = inf
> Warning: NaN or Inf found in input tensor.
> ```
> 
> 标记里有英文字符，是这个问题导致？
> 
> _Originally posted by @v-yunbin in [#51 (comment)](https://github.com/libai3/masr/issues/51#issuecomment-507514335)_

我也是这样，这是什么原因
