### ISSUE TITLE
想知道为什么要用docker？

### ISSUE THREAD

**Issue by ngsford** [libai3/masr#139]
我纯小白啊，真没搞懂为什么

**Comment by lingr7** [comment]
一种潮流吧。用docker部署环境快啊。就跟封装的Anaconda一样，直接把常用库安装好了。Python一个一个库单独安装是不是很麻烦？

**Comment by wentixiaogege** [comment]
还不是怕你配置不好~ 给你节省时间

**Comment by ngsford** [comment]
好嘞，感谢
