### ISSUE TITLE
预训练模型和测试音频文件下载链接已经失效了！！！

### ISSUE THREAD

**Issue by yaakovazat** [libai3/masr#140]
预训练模型和测试音频文件下载链接已经失效了！！！ 希望能够解决一下，谢谢！

如果能放在百度之外的地方，更是好。。。。。。百度网速实在是太快了。。

**Comment by zhengchuan000** [comment]
感谢楼主，如果能更新下预训练模型和测试音频文件就太好了。

**Comment by huxianhe0** [comment]
请问谁还有预训练模型和测试音频文件的下载链接吗？

**Comment by huxianhe0** [comment]
https://github.com/libai3/masr/releases
