### ISSUE TITLE
求TensorFlow实现版本，另外README如果用英文写，可能会吸引国外大牛

### ISSUE THREAD

**Issue by afterthat97** [libai3/masr#2]
如题

**Comment by lukhy** [comment]
英文README我打算另写一份的。
吸引国外用户应该不太可能，毕竟预训练模型只有中文的。
TensorFlow算了吧。等2.0出了再学😄。

**Comment by stereomatchingkiss** [comment]
>TensorFlow算了吧。等2.0出了再学

可以理解，google明明是家超级大公司，打造出来的lib，API却差的让人惊叹，TensorFlow的接口不像是经验老道的程序员设计出来的，更像是由实验室里的博士，硕士弄出来的

**Comment by neoedmund** [comment]
得了吧，这作者啥也不懂就会装逼，贻笑大方。识别出来的什么狗屎，还自称开源界第一？不知道哪来勇气？

**Comment by libai3** [comment]
![Screenshot_20190708_214726](https://user-images.githubusercontent.com/19603362/60815341-002e2280-a1ca-11e9-902f-1908e4665341.png)
Haha, your words just defined you.
