### ISSUE TITLE
啥都别说了，ASRT群里过来的，反手就是一个start！

### ISSUE THREAD

**Issue by deepxuexi** [libai3/masr#36]
还没测试效果，刚好下了那个语言模型，是chineseocr项目上用到的，OCR识别文字不愁训练数据，因为它可以用各种字体和背景图片合成大规模的训练数据，如果语音识别也能够用各种TTS合成的大量语音数据，再加上谷歌SpecAugment来做语音数据增强，那哥您也就不用担心百度的“钞能力”了。
预祝您的项目早日start过万！（不介意的话加个好友呗）

**Comment by libai3** [comment]
谢谢
