### ISSUE TITLE
请问能不能将模型上传到其他空间

### ISSUE THREAD

**Issue by stereomatchingkiss** [libai3/masr#47]
如标题，我是马来西亚人，无法注册百度的账号（为啥不让国外用户注册啊？），没办法下载模型，能不能上传到其他空间去?谢谢

**Comment by lukhy** [comment]
你好，有什么推荐的空间吗？

**Comment by stereomatchingkiss** [comment]
你好，感谢回复
有可能上传到Onedrive、dropbox或mega.nz吗（可能要翻墙？）？
只要是你觉得方便并能让国外用户下载的，我觉得都可以

**Comment by lukhy** [comment]
https://github.com/lukhy/masr/releases

**Comment by stereomatchingkiss** [comment]
谢谢你，总算能下载了 :)
