### ISSUE TITLE
背景噪音问题

### ISSUE THREAD

**Issue by neoedmund** [libai3/masr#55]
录的音频，日常环境总会有背景噪音。 人耳还是比较清楚的能听出语句，但是这个识别只认出一个字之类的。不知是怎么回事，是不是我对现在的语音识别有什么误解？
由于数据比较敏感，需要我说的这种测试数据的话，可以私下发给你，谢谢。

**Comment by v-yunbin** [comment]
训练数据和测试数据不匹配造成的，要想识别你的数据可以用你的同类数据训练模型或者对你数据去噪。

**Comment by neoedmund** [comment]
各种人有各种音色（男的女的，不同年龄的），不知道这个对训练数据有多敏感。我实际测试就是效果很不好，比如，识别结果:
`二海外他哈阿拉化马南来行哈业哈业哈还二和化的华和哈行行还韩和一和的和还和拉拉` , 差的太远了。

**Comment by v-yunbin** [comment]
这个模型是用aishell1数据训练的，数据比较干净，所以还是用干净一点的数据训练。测试噪音大的数据还是有点差。

**Comment by libai3** [comment]
Well, this result doesn't make sense.
Did you use the pretrained network with language model?

**Comment by neoedmund** [comment]
> Well, this result doesn't make sense.
> Did you use the pretrained network with language model?

I don't know if I used language model, though there is a file `lm/zh_giga.no_cna_cmn.prune01244.klm`
The result seem showing not even close to Pinyin(guess the noise result it?). 
I don't know the use case of MASR. For example, 10 persons(strangers) have different voice, should I train for every person? 
Also will MASR add de-noise function build-in? because most recorded audio contains noise.

**Comment by libai3** [comment]
Since you don't know anything, there is nothing I can do to help you.

**Comment by neoedmund** [comment]
> Since you don't know anything, there is nothing I can do to help you.

The readme  is very kind and welcome, but you are not willing to help. WTF!

> 如果你有任何问题，请在issue区提出来，让我知道。issue区也有很多热心的小伙伴，可以帮你解决问题。

问题包括但不限于：

    这个依赖我咋装不上啊？
    这啥下载也太慢了吧？（下载不了啊？）
    我运行到这步咋出错了啊？
    我还是没搞清楚你这个识别原理是啥？
    我发现隔壁某某项目比你这个好使啊？
