### ISSUE TITLE
ctcdecode在各平台编译都不通过...

### ISSUE THREAD

**Issue by primejava** [libai3/masr#60]
这个东西真是费劲,,windows和centos都不行

**Comment by primejava** [comment]
这个模块有没有方便安装的替代品,或者有编译好的包提供使用呢

**Comment by linzongzhu** [comment]
我是win10，不可以在win上用么？

**Comment by primejava** [comment]
不可以 已放弃

**Comment by primejava** [comment]
很让人生气 换了阿里云的ubuntu服务器还是装不上

**Comment by linzongzhu** [comment]
https://blog.csdn.net/u011550545/article/details/87926995#commentsedit
我CSDN找到教程你试试，但是我还没ubuntu。现在去下

**Comment by libai3** [comment]
Non constructive.
